### ISSUE TITLE
Chinese characters are not centered up and down in box

### ISSUE THREAD

**Issue by akschy** [IoaNNUwU/InLine#18]
![image](https://github.com/IoaNNUwU/InLine/assets/44605406/aaca3f45-ec84-42ce-84c9-f265ded794f4)
Aligning the Chinese bottom edge with the English baseline will cause the Chinese character to be biased upwards within the frame, and some Chinese character strokes may overlap with the border.
the box is not center in line and it is lower than the curly braces.
Overall, I think there is no problem with the text but box is drawn too low.

**Comment by IoaNNUwU** [comment]
Thank you for the report.

Hopefully fixed in latest release.

![image](https://github.com/IoaNNUwU/InLine/assets/106328960/4cd4a29a-7b7c-40e7-8579-3206a8064abd)
