### ISSUE TITLE
Seems broken in the latest IntelliJ 2023.2

### ISSUE THREAD

**Issue by ithinkicancode** [IoaNNUwU/InLine#19]
With this plugin enabled, IntelliJ 2023.2 throws error. And not only in-line warnings/errors are *not* shown but it also seems to prevent the warning/error color strip in the sidebar/gutter on the right which is usually visible even without this plugin.

Once this plugin is enabled, the color strip on the right from IntelliJ now displays regions with warnings and errors.

**Comment by IoaNNUwU** [comment]
Fixed in latest 1.2.0 release
