### ISSUE TITLE
Leading space can swallow characters

### ISSUE THREAD

**Issue by xzbdmw** [IoaNNUwU/InLine#24]
<img width="1244" alt="image" src="https://github.com/IoaNNUwU/InLine/assets/97848247/de45eb86-cedc-414b-90b5-3ed691f0e2d4">
I can't move right because I set 4 leading space on errors, version Clion 2023.3.1

**Comment by IoaNNUwU** [comment]
Hi, as far as i can see, you have some type of auto-complition (gray text). But I'm not sure what is the problem here.

Can you please give full description of what are you trying to achieve and what do you mean `can't go right`.

**Comment by xzbdmw** [comment]
like this

https://github.com/IoaNNUwU/InLine/assets/97848247/ebe74b6e-b429-4b26-b2a5-b67a722b2f69

**Comment by IoaNNUwU** [comment]
Oh now I see, thank you !

**Comment by IoaNNUwU** [comment]
Fixed in 1.3.0
